-- ==============================================================================
-- DDL: CRIAÇÃO DA TABELA FATO DA ESTUFA JAMESTOWN
-- ==============================================================================
CREATE TABLE FACT_JAMESTOWN_DATA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    module_id VARCHAR2(10),
    ph NUMBER(4,2),
    humidity NUMBER(5,2),
    co2 NUMBER(6,2),
    temperature NUMBER(4,2),
    radiation NUMBER(5,2),
    predicted_class NUMBER(2),
    nasa_alert NUMBER(1)
);

-- ==============================================================================
-- DQL: CONSULTAS ANALÍTICAS E CRUZAMENTO DE DADOS (IOT + AI + CLIMA ESPACIAL)
-- ==============================================================================

-- Validação de inserção
SELECT * FROM FACT_JAMESTOWN_DATA;

/* 1. Diagnóstico Geral de Saúde das Estufas (ACV)
Objetivo: Contar o total de amostras lidas pela Visão Computacional e categorizar quantas estão saudáveis, com estresse ou com fungos por setor.
*/
SELECT 
    module_id AS SETOR_DA_BASE,
    COUNT(*) AS TOTAL_AMOSTRAS_ANALISADAS,
    SUM(CASE WHEN predicted_class = 0 THEN 1 ELSE 0 END) AS PLANTAS_SAUDAVEIS,
    SUM(CASE WHEN predicted_class = 1 THEN 1 ELSE 0 END) AS CASOS_ESTRESSE_HIDRICO,
    SUM(CASE WHEN predicted_class = 2 THEN 1 ELSE 0 END) AS CASOS_FUNGO_CRITICO
FROM FACT_JAMESTOWN_DATA
GROUP BY module_id
ORDER BY CASOS_FUNGO_CRITICO DESC;

/* 2. Médias de Suporte à Vida por Módulo
Objetivo: Calcular a temperatura, umidade e CO2 médios da estufa para o painel do comandante, garantindo que o ambiente está seguro.
*/
SELECT 
    module_id AS SETOR,
    ROUND(AVG(temperature), 2) AS TEMP_MEDIA_CELSIUS,
    ROUND(AVG(humidity), 2) AS UMIDADE_MEDIA_PCT,
    ROUND(AVG(co2), 2) AS CO2_MEDIO_PPM,
    ROUND(AVG(ph), 2) AS PH_MEDIO_AGUA
FROM FACT_JAMESTOWN_DATA
GROUP BY module_id;

/* 3. Auditoria de Violações de Radiação (Alerta NASA)
Objetivo: Filtrar apenas os momentos de perigo, cruzando picos de radiação interna dos sensores com os alertas reais de tempestade solar.
*/
SELECT 
    TO_CHAR(timestamp, 'DD/MM/YYYY HH24:MI') AS DATA_HORA_OCORRENCIA,
    module_id AS SETOR_AFETADO,
    radiation AS NIVEL_RADIACAO_MSV,
    CASE WHEN nasa_alert = 1 THEN 'ALERTA EXTERNO NASA ATIVO' ELSE 'NORMAL' END AS STATUS_CLIMA_ESPACIAL
FROM FACT_JAMESTOWN_DATA
WHERE radiation > 0.50 OR nasa_alert = 1
ORDER BY timestamp DESC;

/* 4. Correlação de Clima com Doenças Botânicas
Objetivo: Cruzar as variáveis físicas (Temperatura e Umidade) com o diagnóstico da Inteligência Artificial, para verificar se o estresse das plantas está associado a picos de calor.
*/
SELECT 
    CASE predicted_class 
        WHEN 0 THEN 'Saudável'
        WHEN 1 THEN 'Estresse Hídrico/Nutricional'
        WHEN 2 THEN 'Infecção por Fungos'
        ELSE 'Sem Diagnóstico'
    END AS DIAGNOSTICO_DA_IA,
    COUNT(*) AS OCORRENCIAS,
    ROUND(AVG(temperature), 2) AS TEMP_MEDIA_ASSOCIADA,
    ROUND(AVG(humidity), 2) AS U